LisaDziuba/Awesome-Design-Tools

- README.md
Thanks for the great list of design tools 🙌
Here's the one my team's working on: a version control system for design files built on top of Git — [Versions](https://versions.sympli.io).
> Add Versions under Design System Tools

- README.md
I'm surprised that many people don‘t realize how powerful Keynote actually is for building simple prototypes. And this tool literally comes pre-installed on macOS and iOS!
Must have 💪
> Add Keynote under Prototyping Tools

- README.md
[Sim Daltonism](https://michelf.ca/projects/sim-daltonism/) is an awesome tool that lets you explore how you designs look from the perspective of a color blind person 👀
> Add Sim Daltonism to Accessibility Tools

- README.md
Signed-off-by: Paramdeo Singh <paramdeo@paramdeo.com>
> Added Vectr, Folio, Plant, Fathom, Heap

- README.md
Added item under the `User Flow Tools` section
> Added Google Drawing

- README.md
* Added STUDIO to "Design to Code Tools"
> Added STUDIO

- README.md
Added: Colourcode, NIPPON COLORS, and UI Gradients
> Add more color picker tools

- README.md
- Added Readymag to "Design to Code Tools"
- Added "Icons Tools" Topic 
- Added "IconJar" to new "Icons Tools" Topic 
- "Mixpane" changed to "Mixpanel"
- Fixed document navigation from absolute links to anchors (relevant for forks)
> Readymag, IconJar, Mixpanel, Doc Navigation

- README.md
Excellent list of resources and tools. Thanks for putting it together. Hopefully I can help contribute to this list and the community.
> Various grammar fixes

- README.md
Kap (https://getkap.co) is a very simple screen recorder that lets you export to GIF, MP4, and other video formats.
> Add Kap to the list of screenshot tools

- README.md
Signed-off-by: Paramdeo Singh <paramdeo@paramdeo.com>
> Added Bootstrap Studio & Pinegrow

- README.md
Sketch.systems is pretty interesting tool that allows using interactive state machines (with optionally attaches code or figma templates) to prototype product flow.
> Add Sketch.systems

- README.md
Added 
- "Stock Photos Tools" Topic
- "[Zoommy](http://zoommyapp.com)" app to "Stock Photos Tools" Topic
> Adding Stock Photos Tools

- README.md
add coolors.co as a color scheme generator
> add coolors.co

- README.md
- Added ScreenSpace.io
- Added Cleanmock
> Adding ScreenSpace.io

- README.md
Alphabetize section titles (and tool titles) to match ToC order.
Change "References" section title to "Addendum".
> Alphabetize Content.

- README.md
> Added Amplitude Analytics

- README.md
One more website to photo resources.
> Added FreePhotos.cc

- README.md
It's a very useful app! 
https://sipapp.io/
> Add Sip 🖌️

- README.md
Add MURAL under Collaboration Tools
> Added MURAL

- README.md
> Added BeatFlyer

- README.md
Per the Contribution Guidelines I added missing full stops to the
descriptions and removed trailing whitespace.
> Removed trailing whitespace & added full stops.

- README.md
- Add new tool to list
- Fix small typography issues
- Readability improvements to the Markdown structure
> Add new tool to the list + fix small typography issues

- README.md
Signed-off-by: Paramdeo Singh <paramdeo@paramdeo.com>
> Added Burst and Pixabay

- README.md
Adds axe to accessibility tools.
https://www.deque.com/axe/
> Add axe to accessibility tools

- README.md
Hey, as the title suggests I think this would be a valuable addition. 😇
> Add Adobe fonts

- README.md
Wonderful list :) I've added Typeface app - a font manager for designers
> Added Typeface app

- README.md
Hey @LisaDziuba, I found your Awesome-Deisgn-Tools project while 🏄 surfin' the web and thought it might be a good idea to mention that the Framer Team Store is a great place for creating and maintaining design systems. While there I improved the Framer X copy a bit.
(full disclaimer I'm an engineer at Framer 😬)
> Improved Framer X copy and mentioned Framer X team store

- README.md
Thank you for the great list!
**Piskel** doesn't quite fit into "Icons Tools" category (it's about sprites and pixel art in general), so a new category is introduced. And it's [open-source](https://github.com/piskelapp/piskel)! :)
**Aseprite** [looks](https://www.aseprite.org/docs/tutorial/) very solid, @HallerPatrick thanks for the suggestion!
> Add Piskel and introduce the "pixel art tools" category

- README.md
Krita is a painting and graphic design software, Just color picker is a portable color picker and editor.
> Added Krita and Just Color Picker, rearranged some entries

- README.md
> Added information architecture tools to the list

- README.md
Hello, I've added two resources that help designers at the end stages of their logo design projects.
> Added Logo Design Section with Logo Package Express and Logo Lab

- README.md
Adding [Keyshape](https://www.keyshapeapp.com/) into animation tools. Great tool to export animated SVGs.
> Add Keyshape

- README.md
Three tools added for screen capture/record a video
> Screen recording software, Font Tools add

- README.md
Updated `Haiku` animation resource to reflect new name.
> Updated Haiku in Animation Tools

- README.md
I've added [Lens Studio](https://lensstudio.snapchat.com/), Snapchat's platform to create AR experiences
> Add Lens Studio

- README.md
Added `Relay for Figma` to Version Control for Designers section. Relay bills itself as a tool that offers Continuous Design Delivery.
> Added resources to Version Control & Illustrations section

- README.md
Add a new section for design pattern, user flow, and task exploration tools for guidance and inspiration
> Add Design Pattern and Inspiration Tools

- README.md
@LisaDziuba Just added Slack and Airtable, tools I totally love using and think is a great add to this amazing list 😃
> New Collaboration Tool Add

- README.md
> Add LogRocket to experience monitoring tools section

- README.md
Added Flare link which lets you create cool animations for your app or game. It also has support for the Flutter framework.
Added Flow link which lets you create animations from your Sketch projects and export the code for web, SVG or iOS.
> Add Flow and Flare tools

- README.md
Added [Wireflow](http://wireflow.co) User flow tool.
Wireflow is free, online and open source tool for creating beautiful user flow prototypes. No Photoshop skills required!
Source code is available on Github https://github.com/vanila-io/wireflow
> Add Wireflow

- README.md
Added CodeMyUI and Inspiration UI to a new section called UI Inspiration. added a bunch of labels to free stuff in Design Pattern and Inspiration Tools.
> suggesting a new category UI Inspiration

- README.md
> Add LogRocket to Visual Debugging Tools

- README.md
> Milanote (Collaboration Tools)

- README.md
Wakamai Fondue is a fantastic little tool with a great name. It lets you explore a font's glyphs, languages, and layout features. It also generates a nice stylesheet that you can put in your website.
> Added Wakamai Fondue to the font tools section

- README.md
> Added Symbol Design System

- README.md
Pencil is built for the purpose of providing a free and open-source GUI prototyping tool that people can easily install and use to create mockups in popular desktop platforms.
> Rmpr patch pencil

- README.md
Added [Grapedrop](https://grapedrop.com/) to `Design to Code Tools` category :)
> Add Grapedrop

- README.md
UXPin is a complete design platform that has multiple tools to cover entire design process. Therefore it fits into multiple categories on the list.
I took a liberty to add informations about UXPin tools to other categories than just Prototyping.
UXPin also has the free plan that can be used with most of it's tools, so I've added _free_ label to those.
> UXPin - added info in categories that fit

- README.md
To add new design tool topic:
- enter new line
- type <article id="design-tool-name"> (make sure the id is as same as link to the topic in table of content)
- leave the next line blank
- write content you desire
- leave next line empty again
- type </article> in the next file to end topic
take any <article id="some-topic"> as an example.
FAQs
- What is <div class="hidden-in-page"></div>? 
+ The content that won't be visible on the landing page. Include everything inside this tag and it will only be visible in markdown file.
- What about <div class="nav"></divi>?
+ This is a container for navigation. There's no need to modify html tag. You can add new links to topics with no problems.
- Can I write new tags?
+ Yes. Please be sure that there's some purpose for it. You can add your custom …
> Preparation for landing page

- README.md
> Add links to Stylie and Mantra

- README.md
> Adding UserBit and Reframer to User Research category

- README.md
sentences in 'Animation Tools', 'Augmented Reality Tools' and 'Collaboration Tools' were a little awkward to read. Made some edits to make things more clear.
> Sentence updates in ReadMe

- README.md
> Add CleanShot to Screnshot Software

- README.md
* [x ] I put links in the correct format: ``[Tool](link) — description.``
* [x ] My description starts with the lower-case letter and ends with the full stop.
* [x ] I put the tool in the alphabetical order.
* [x ] I put the tool only to one category.
> Added Mattermost to Collaboration Tools

- README.md
> Add PixelSnap to Visual Debugging Tools

- README.md
> Added Mixed.io to collab tools

- README.md
> Add Sunsama to Collaboration Tools

- README.md
> Added Prime & SQUID

- README.md
Design tool for prototyping conversational experiences for Alexa, Google Assistant and more.
> Added Botmock to the list

- README.md
> Add PageXL to No Code Tools

- README.md
> Add Picular & Remove.bg

- README.md
> Added User Interviews to User Research Tools

- README.md
> Added sound repository and sound design tools

- README.md
> add EOS Design System to the list of Design Systems

- README.md
> Added Sparkle

- README.md
> added WebSequenceDiagrams

- README.md
> Added tools to the Learning Design category

- README.md
> Added Tinkercad

- README.md
> add entry in Prototyping Tools

- README.md
Added:
- Design Inspiration: One Page Love
- Illustration: ManyPixels 
Fixed:
- "Mixed" free icon svg not displaying correctly
> Added One Page Love and ManyPixels

- README.md
> Added Relay to the Design Handoff section

- README.md
> Adding Waveguide to Design Inspiration.

- README.md
> Add Wizlogo to Logo Design

- README.md
> Add Behance to the Design Inspiration section

- README.md
Add Pagecloud to "Design to Code" Section
> Add PageCloud

- README.md
> Added colorwise.io

- README.md
* [x ] I put links in the correct format: ``[Tool](link) — description.``
* [x ] My description starts with the lower-case letter and ends with the full stop.
* [ x] I put the tool in the alphabetical order.
* [x ] I put the tool only to one category.
> Added Voiceflow to design tool list

- README.md
> add `Viz Palette` (color picker)

- README.md
> Add PaintCode to the list

- README.md
It's a great piece of software, but you have to pay to unlock most of its features 👍
> Mindnode is a "freemium" app

- README.md
> Added Prott

- README.md
> Add wannapik.com into illustrations/vectors

- README.md
> Add GSAP to animation tools

- README.md
> Added Anima.

- README.md
added https://joeschmoe.io/ to the Illustrations section
> added JoeSchmoe

- README.md
> Added Ficture

- README.md
> Add Catalog and Storybook to Design System Tools

- README.md
Aseprite is paid, but you can compile it yourself: https://github.com/aseprite/aseprite.
> Aseprite is open source

- README.md
Development browsers help designers and developers create websites faster, and offers a better way to test and validate designs. They're upcoming and I think they deserve their own category :) Full disclosure: I built Polypane.
> Add new category: development browsers

- README.md
> Add GradientsList to Gradients tools

- README.md
> Added UserGuiding

- README.md
Hi Lisa, I've added [Screenzy](https://screenzy.io/) to the Mockup category, and updated the [PageXL](https://pagexl.com/) description since it can now make online stores.
Thanks for your awesome work.
Regards,
Yann
> Adding Screenzy to mockup tools

- README.md
> Add Modulz to design system tools

- README.md
* [x ] I put the tool in the alphabetical order.
> Added Smartlook

- README.md
> Added Sticktail

- README.md
Hi! I'm adding Web Font Preview and removing some trailing whitespace. Thank you for your work!
> Add Web Font Preview to Font Tools

- README.md
* [x ] I put links in the correct format: ``[Tool](link) — description.``
* [x ] My description starts with the lower-case letter and ends with the full stop.
* [x ] I put the tool in the alphabetical order.
* [x ] I put the tool only to one category.
> Added Mediamodifier to Mockup tools.

- README.md
* [NA] I added the appropriate labels: free, open-source or mac.
> Added Handrail

- README.md
* [ X] I put the tool in the alphabetical order.
> Added TwitPile.com!

- README.md
> Added Image Color Picker in Color Picker Tools

- README.md
* [Dokyu Motion](https://3dmybusiness.com) — Dokyu simplifies motion design in After Effects so any editor can tell stories that won′t be ignored.
> Added my tool Dokyu Motion for consideration

- README.md
> Added Motion Icons

- README.md
> Added Drama app

- README.md
> Adding IDF interaction design foundation

- README.md
hi! came here to fix a tiny typo, but also wanted to mention visbug has many a11y features
thanks! hope this finds you well.
> fixes typo "categoty" and made prompt plural

- README.md
> Add OriginalMockups item in README.

- README.md
> Adds droplr.com

- README.md
> Add CoreUI Icons

- README.md
Completely vector, animated icons for interfaces
> ➕Movin Icons (Icons Tools)

- README.md
I added a new item(Freepik) in Illustrations category in Awesome Design Tools  in README file
we can find numerous graphics, Vectors and other art free on this site.
> Add Freepik in illustration category

- README.md
> Added Moqhub

- README.md
* [ x] I put links in the correct format: ``[Tool](link) — description.``
* [ x] My description starts with the lower-case letter and ends with the full stop.
* [x ] I put the tool in the alphabetical order.
* [x ] I added the appropriate labels: free, open-source or mac.
* [x ] I put the tool only to one category.
> add: Govisually

- README.md
> Added Toolabs as a Design System Tool

- Awesome-Design-Plugins.md
> Added Toolabs DSM as a plugin for Adobe XD

- README.md
> Fixed spelling mistakes in README.md

- Awesome-Design-Plugins.md
Added 2 new Sketch plugins
- Sketch Guides
- Symbol Browser
> Added 2 new Sketch plugins

- README.md
> Added Color Hunt to color picker tools

- README.md
> Added https://interplayapp.com/ 

- README.md
> added WriteMaps to Information Architecture

- Awesome-Design-Plugins.md
- README.md
> Added Useberry

- README.md
> Added EasyLogic Studio

- Awesome-Design-Plugins.md
> add Crowdin's Sketch plugin

- README.md
> feat: Add Iconset to category Icons Tools

- README.md
> Added Kodika in Readme.md

- README.md
> Add calcolor to color picker tools

- README.md
I've redesigned this tool completely and it has a new website and URL (I'm the creator of this and added this original listing).
> Update existing listing for Motion Icons

- Awesome-Design-Conferences.md
Updated the description for CreativePro Week Conference in June
> Revised CreativePro Week listing

- Awesome-Design-Conferences.md
> Added An Event Apart Conference listings

- Awesome-Design-Plugins.md
> Added Crowdin plugin for Figma.md

- README.md
> Add "LiveSession" to "Experience Monitoring"

- Awesome-Design-Plugins.md
> Added the Funk Creatives tool for Adobe XD to the list of resources

- README.md
> Add Norde Source to category Icons Tools

- README.md
> Add SceneLab to mockup tools

- README.md
> Add font site

- README.md
> Add Figma Training to README

- README.md
> Add Excalidraw to Collaboration Tools section

- README.md
> Add Octopus.do to README

- README.md
> Added zipBoard

- README.md
> Add SaaS Landing Page to Design Inspiration cat

- README.md
> Removed Appear.in from the list.

- README.md
> Updates No Code Tools

- README.md
> Updated Bubble URL

- Awesome-Design-Plugins.md
> Added Attention Insight plugin to Analytics section
